# npx antora --clean --fetch antora-playbook.yml
# or
# npx antora antora-playbook.yml
antora:
  extensions:
    - '@antora/site-generator-ms'
    - ./lib/embargo.js

site:
  title: OpenShift Container Platform Documentation
  url: https://docs.openshift.com
  start_page: openshift-container-platform::welcome/index.adoc
  robots: allow
  keys:
    google_analytics: TBD
    nav_groups: |
      [
      ]
git:
  ensure_git_suffix: false
  fetch_concurrency: 10
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  sources:
    - url: .
      branches: HEAD
      start_path: home
    - url: https://github.com/aireilly/openshift-docs-antora
      branches:
        - main
asciidoc:
  attributes:
    site-navigation-data-path: _/js/site-navigation-data.js
    enable-cmos: ''
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    page-toclevels: 1@
    xrefstyle: short
    # the url-issues and url-issues-* attributes configure the URLs
    url-issues: https://issues.redhat.com/browse
    url-issues-jscbc: https://issues.redhat.com/browse
    url-issues-av: https://redhatcloud.atlassian.net/browse
    kroki-server-url: http://3.91.133.254:9500
    kroki-fetch-diagram: true
  extensions:
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-jira-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
    - ./lib/markdown-block.js
    - asciidoctor-kroki
    - asciidoctor-external-callout
ui:
  bundle:
    url: https://github.com/aireilly/redhat-antora-ui/releases/download/2/ui-bundle.zip
output:
  dir: ./public
