# npx antora --clean --fetch antora-playbook.yml
# or
# npx antora antora-playbook.yml
antora:
  extensions:
    - '@antora/site-generator-ms'
    - ./lib/embargo.js

site:
  title: OpenShift Container Platform Documentation
  url: https://docs.openshift.com
  start_page: home::index.adoc
  robots: allow
  keys:
    google_analytics: TBD
    nav_groups: |
      [
      { "title": "OpenShift", "startPage": "openshift-container-platform::welcome/index.adoc", "components": ["openshift-container-platform"] },
      { "title": "OpenShift on AWS", "startPage": "openshift-container-platform::welcome/index.adoc", "components": ["openshift-container-platform"] },
      { "title": "OpenShift on Microsoft Azure", "startPage": "openshift-container-platform::welcome/index.adoc", "components": ["openshift-container-platform"] },
      { "title": "OpenShift on Bare Metal", "startPage": "openshift-container-platform::welcome/index.adoc", "components": ["openshift-container-platform"] }
      ]
git:
  ensure_git_suffix: false
  fetch_concurrency: 10
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  sources:
    - url: .
      branches: HEAD
      start_path: home
    - url: https://github.com/aireilly/openshift-docs-antora
      branches: [main]
      start_path: docs
asciidoc:
  attributes:
    site-navigation-data-path: _/js/site-navigation-data.js
    enable-cmos: ''
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    page-toclevels: 1@
    xrefstyle: short
    # the url-issues and url-issues-* attributes configure the URLs
    url-issues: https://issues.redhat.com/browse
    url-issues-jscbc: https://issues.redhat.com/browse
    url-issues-av: https://redhatcloud.atlassian.net/browse
  extensions:
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-jira-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
    - ./lib/markdown-block.js
    - asciidoctor-external-callout
ui:
  bundle:
    url: /home/aireilly/redhat-antora-ui/build/ui-bundle.zip
output:
  dir: ./public
