= OpenShift Container Platform Documentation
:page-meta-zd-site-verification: odvin2siwmodz30xrtxq
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:
:collapsible:

= OpenShift Container Platform

Red Hat® OpenShift® Container Platform is a consistent hybrid cloud foundation for building and scaling containerized applications. Red Hat OpenShift is trusted by thousands of customers in every industry to deliver business-critical applications, whether they’re migrating existing workloads to the cloud or building new experiences for customers. It’s also backed by one of the leading Kubernetes contributors, Red Hat.

== Get Started
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.Install OpenShift Container Platform

[.content]
You can install OpenShift Container Platform on installer-provisioned or user-provisioned infrastructure. The OpenShift Container Platform installation program provides the flexibility to deploy OpenShift Container Platform on a range of different platforms.

xref:cloud::index.adoc[Installing OpenShift Container Platform]

[.column]
====== {empty}
.Understand OpenShift Container Platform development

[.content]
Learn the different types of containerized applications, from simple containers to advanced Kubernetes deployments and Operators.

xref:server.adoc[Understanding OpenShift Container Platform development]

[.column]
====== {empty}
.Run your workloads on OpenShift Container Platform

[.content]
The Service Binding Operator enables application developers to easily bind workloads with Operator-managed backing services by automatically collecting and sharing binding data with the workloads. The Service Binding Operator improves the development lifecycle with a consistent and declarative service binding method that prevents discrepancies in cluster environments.

xref:redhat::introduction.adoc[Running workloads on OpenShift Container Platform]

++++
</div>
++++
